services:
  - type: web
    name: notion-rss-bot-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
