name: Deploy to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'server.py'
      - 'static/**'
      - 'requirements.txt'
      - 'render.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          echo "🚀 Deployment su Render"
          echo "📊 Il server sarà sempre attivo"
          echo "🔗 Configura le variabili d'ambiente su Render"
          echo "📝 URL: https://your-app-name.onrender.com"
