name: Deploy to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'server.py'
      - 'static/**'
      - 'requirements.txt'
      - 'railway.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railway/deploy@v1
        with:
          service: ${{ secrets.RAILWAY_SERVICE_NAME }}
          token: ${{ secrets.RAILWAY_TOKEN }}

      - name: Wait for deployment
        run: |
          echo "🚀 Deployment completato su Railway"
          echo "📊 Il server è ora sempre attivo"
          echo "🔗 URL: https://${{ secrets.RAILWAY_SERVICE_NAME }}.railway.app"
