name: Idealista Unified (Populate + Export)

on:
  schedule:
    # Esegui ogni giorno alle 8:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Permette esecuzione manuale

permissions:
  contents: write   # serve per fare commit del data-idealista.json

jobs:
  idealista-unified:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests
        
    - name: Install Node.js dependencies
      run: |
        npm install
        
    - name: Populate Idealista Database
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        IDEALISTA_API_KEY: ${{ secrets.IDEALISTA_API_KEY }}
        IDEALISTA_API_SECRET: ${{ secrets.IDEALISTA_API_SECRET }}
        IDEALISTA_NOTION_DATABASE_ID: ${{ secrets.IDEALISTA_NOTION_DATABASE_ID }}
      run: |
        python idealista/populate_idealista.py
        
    - name: Export Idealista Data
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        IDEALISTA_NOTION_DATABASE_ID: ${{ secrets.IDEALISTA_NOTION_DATABASE_ID }}
      run: |
        node idealista/fetch_idealista.js
        
    # Pull delle modifiche remote prima del commit
    - name: Pull modifiche remote
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git pull origin V2 --rebase || echo "No remote changes to pull"

    - name: Commit e push se ci sono cambiamenti
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "feat: aggiorna data-idealista.json"
        file_pattern: |
          public/data-idealista.json
        commit_user_name: 'GitHub Action'
        commit_user_email: 'action@github.com'
        commit_options: '--no-verify'
        push_options: '--force-with-lease'
