name: Export Idealista Data

on:
  schedule:
    # Esegui ogni 6 ore daje
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permette esecuzione manuale
  workflow_run:
    workflows: ["Populate Idealista Database"]
    types: [completed]

jobs:
  export-idealista:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Export Idealista Data
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        IDEALISTA_NOTION_DATABASE_ID: ${{ secrets.IDEALISTA_NOTION_DATABASE_ID }}
      run: |
        node scripts/fetch_idealista.js
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        force_orphan: true
