name: Aggiorna dati e esegui script

on:
  schedule:
    - cron: "0 * * * *"   # ogni ora (al minuto 0)
  workflow_dispatch:      # esecuzione manuale dal tab Actions

permissions:
  contents: write   # serve per fare commit del data.json

jobs:
  update-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Python per lo script principale
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze Python
        run: pip install -r requirements.txt

      # Esegui lo script Python principale PRIMA
      - name: Esegui script principale
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          RSS_URL: ${{ secrets.RSS_URL }}
        run: python main.py

      - name: Usa Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Aggiorna data.json da Notion DOPO
      - name: Esegui script Notion → data.json
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node scripts/fetch_notion.js

      - name: Commit e push se ci sono cambiamenti
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: aggiorna public/data.json"
          file_pattern: public/data.json
