name: Aggiorna data.json da Notion

on:
  schedule:
    - cron: "0 * * * *"   # ogni ora (al minuto 0)
  workflow_dispatch:      # esecuzione manuale dal tab Actions

permissions:
  contents: write   # serve per fare commit del data.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Usa Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Nessuna dipendenza: usiamo solo fetch di Node 20
      - name: Esegui script Notion → data.json
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node scripts/fetch_notion.js

      - name: Commit e push se ci sono cambiamenti
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: aggiorna public/data.json"
          file_pattern: public/data.json
